"""
Django settings for BRAVO project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os, sys
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if os.path.exists(os.path.join(BASE_DIR, '.env')):
    with open(os.path.join(BASE_DIR, '.env'), "r") as file:
        config = json.load(file)
    for key in config.keys():
        os.environ[key] = config[key]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Hard-drive Database Initiation
DATASERVER_PATH = os.environ.get('DATASERVER_PATH')
if not DATASERVER_PATH.endswith(os.path.sep):
    DATASERVER_PATH += os.path.sep
    os.environ["DATASERVER_PATH"] = DATASERVER_PATH
    
os.makedirs(DATASERVER_PATH + "cache", exist_ok=True)
os.makedirs(DATASERVER_PATH + "imaging", exist_ok=True)
os.makedirs(DATASERVER_PATH + "raws", exist_ok=True)
os.makedirs(DATASERVER_PATH + "recordings", exist_ok=True)
os.makedirs(DATASERVER_PATH + "visualization", exist_ok=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not (os.environ.get('DJANGO_MODE') == "PRODUCTION")

CSRF_TRUSTED_ORIGINS = ["http://localhost:27286", os.environ.get('SERVER_ADDRESS')]
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_COOKIE_HTTPONLY = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIIE_HTTPONLY = True
SESSION_COOKIE_AGE = 3600*1  # 1 hour

ALLOWED_HOSTS = ["localhost", "127.0.0.1", os.environ.get('SERVER_HOST')]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'Server'
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "Server.Middlewares.ErrorHandler.ErrorHandlingMiddleware",
]

ROOT_URLCONF = 'BRAVO.urls'
STATIC_ROOT = '/static/'
STATIC_URL = '/resources/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Template Engine for Server-Side Rendering
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Authentication for Standalone Version should use basic auth without Tokens
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'Server.authentication.BRAVOAPIAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

WSGI_APPLICATION = 'BRAVO.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

BRAVODatabase = os.environ.get('BRAVO_DATABASE')
if BRAVODatabase:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('BRAVO_DATABASE'),
            'USER': os.environ.get('BRAVO_DATABASE_USER'),
            'PASSWORD': os.environ.get('BRAVO_DATABASE_PASSWORD'),
            'HOST': os.environ.get('BRAVO_DATABASE_HOST'),
            'PORT': os.environ.get('BRAVO_DATABASE_PORT'),
            'PROTOCOL': "tcp",
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
            },
        }
    }

elif not os.path.exists(os.path.join(BASE_DIR, 'mysql.config')):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {
                'read_default_file': os.path.join(BASE_DIR, 'mysql.config'),
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "Server.PlatformUser"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Logging
LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "bravo.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "level": "DEBUG",
            "handlers": ["file"],
        },
    },
    "formatters": {
        "verbose": {
            "format": "{name} {levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django DB Automatic Reconnect
import importlib

from django.conf import settings
from django.db.backends.utils import CursorWrapper

for name, config in settings.DATABASES.items():
    module = importlib.import_module(config["ENGINE"] + ".base")

    def ensure_connection(self):
        if self.connection is not None:
            try:
                with CursorWrapper(self.create_cursor(), self) as cursor:
                    cursor.execute("SELECT 1")
                return
            except Exception:
                pass

        with self.wrap_database_errors:
            self.connect()

    module.DatabaseWrapper.ensure_connection = ensure_connection
    