# Generated by Django 6.0.6 on 2026-07-16 18:43

import django.db.models.deletion
import modules.HelperFunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0006_authenticationtokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleHealth',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('auth', models.JSONField(default=dict)),
                ('date_periods', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
            ],
        ),
    ]
