# Generated by Django 6.0.6 on 2026-08-12 17:44

import modules.HelperFunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_googlehealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCache',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=512)),
                ('type', models.CharField(default='', max_length=128)),
                ('message', models.CharField(default='', max_length=2048)),
                ('response', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
    ]
