# Generated by Django 6.0.6 on 2026-08-12 17:48

import modules.HelperFunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0008_llmcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcache',
            name='date',
            field=models.FloatField(default=modules.HelperFunctions.current_time),
        ),
    ]
