# Generated by Django 6.0.6 on 2026-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0009_llmcache_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='fs_scaling_factor',
            field=models.FloatField(default=1),
        ),
    ]
