FROM ubuntu:20.04

ENV DATASERVER_PATH=/usr/src/BRAVO/BRAVOStorage/
ENV PYTHONPATH=/usr/src/BRAVO/modules/python-scripts

WORKDIR /usr/src/BRAVO
COPY . .

RUN mkdir BRAVOStorage && \ 
    apt-get update && \
    apt-get install cron python3 python3-pip libjpeg-dev libjpeg8-dev libpng-dev libmysqlclient-dev -y && \
    pip3 install -r requirements.txt

COPY cron-job /etc/cron.d/cron-job

RUN chmod 0644 /etc/cron.d/cron-job && \
    crontab /etc/cron.d/cron-job

EXPOSE 3001

CMD ["cron","&&","tail","-f","/var/log/cron.log"]
