# Generated by Django 4.0.6 on 2023-05-13 22:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedRecordingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deidentified_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_deidentified_id', models.UUIDField(default=uuid.uuid4)),
                ('recording_list', models.JSONField(default=list)),
                ('recording_type', models.JSONField(default=list)),
                ('analysis_name', models.CharField(default='Default', max_length=255)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
