# Generated by Django 4.0.6 on 2023-05-22 19:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_combinedrecordinganalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(default='', max_length=255, unique=True)),
                ('institute', models.CharField(default='Mobile', max_length=255)),
                ('unique_user_id', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('configuration', models.JSONField(default=dict)),
                ('linked_patient_id', models.UUIDField(default=uuid.uuid1)),
                ('is_active', models.BooleanField(default=False)),
                ('active_token', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
