# Generated by Django 4.0.6 on 2023-10-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_externalrecording_recording_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='perceptsession',
            name='session_info',
            field=models.JSONField(default=dict),
        ),
    ]
