# Generated by Django 4.0.6 on 2024-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_researchaccesssharelink_authorized_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='customannotations',
            name='event_type',
            field=models.CharField(default='Streaming', max_length=255),
        ),
    ]
