# Generated by Django 4.0.6 on 2024-04-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_brainsenserecording_neuralactivityrecording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientcustomevents',
            old_name='brainsense_psd',
            new_name='neural_psd',
        ),
    ]
