# Generated by Django 4.0.6 on 2024-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_rename_brainsense_psd_patientcustomevents_neural_psd'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedrecordinganalysis',
            name='analysis_label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
